version: '3'
services:
  spark-node:
    image: spark_1node-image
    container_name: spark-node
    hostname: spark-driver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4040:4040
    volumes:
      - ./app:/home/sam/app